name: Packaging using jPackage
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  ubuntu-latest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with: {java-version: '21', distribution: temurin}
    - name: Package application
      run: sh ./package.sh
    - name: Upload Package Artifact
      uses: actions/upload-artifact@v3
      with:
        name: ur-package-ubuntu
        path: |
          output/*.deb
  windows-latest:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with: {java-version: '21', distribution: temurin}
    - name: Package application
      run: package.bat
      shell: cmd
    - name: Upload Package Artifact
      uses: actions/upload-artifact@v3
      with:
        name: ur-package-windows
        path: |
          output/*.exe
          output/*.msi
  macos-latest:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with: {java-version: '21', distribution: temurin}
    - name: Package application
      run: sh ./package.sh
    - name: Upload Package Artifact
      uses: actions/upload-artifact@v3
      with:
        name: ur-package-macos
        path: |
          output/*.pkg